### PR TITLE
parse and analyse full UCI info output

### PR DESCRIPTION
**Pull request by robertnurnberg**
As agreed on discord:

* We drop the counts of complete PVs.
* We check the full engine's output for better/wrong mates and/or incomplete PVs.

Patch:
```
Using ../stockfish/sf16 on matetrack.epd with --nodes 1000
Engine ID:     Stockfish 16
Total fens:    6556
Found mates:   62
Best mates:    45

Parsing the engine's full UCI output, the following issues were detected:
Bad PVs:       68
```

Master:
```
Using ../stockfish/sf16 on matetrack.epd with --nodes 1000
Engine ID:     Stockfish 16
Total fens:    6556
Found mates:   62
Best mates:    45
Complete PVs:  55/62
Complete best PVs:  42/45
Bad PVs:       7
```

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Pushed a change that leads to slightly less output by default: only the first time an issue occurs for a FEN it will be printed to stdout. The option `--showAllIssues` can be used to see all offending UCI info lines.

I also added a paragraph to the readme, so that users get some ideas what the reported numbers mean.

**Comment by robertnurnberg** [comment]
Putting to draft, as I found an inconsistency.

Master:
```
Using ./stockfish on matetrack.epd with --nodes 1000000
Engine ID:     Stockfish dev-20240608-e271059e
Total fens:    6556
Found mates:   3419
Best mates:    2518
Complete PVs:  3418/3419
Complete best PVs:  2518/2518
Bad PVs:       1
```

Patch:
```
Using ./stockfish on matetrack.epd with --nodes 1000000
Engine ID:     Stockfish dev-20240608-e271059e
Total FENs:    6556
Found mates:   3436
Best mates:    2522

Parsing the engine's full UCI output, the following issues were detected:
Bad PVs:       3   (from 2 FENs)
```

This could be to do with the slightly different way we request the info lines from python chess? My treatment of the queue of (mate,pv) tuples seems to be correct: so once queue is empty, we must be dealing with final (mate,pv) pair from the analysis....

**Comment by robertnurnberg** [comment]
With binary search I found one FEN that triggers difference in master and patch for sf-dev: `8/3p4/1p4p1/1P1N2Nb/KP1kB1p1/PP4B1/8/8 w - - bm #7; 00:10;`.

Master:
```
Using ./stockfish on left.epd with --nodes 1000000
Engine ID:     Stockfish dev-20240608-e271059e
Total fens:    1
Found mates:   0
Best mates:    0
```

Patch:
```
Using ./stockfish on left.epd with --nodes 1000000
Engine ID:     Stockfish dev-20240608-e271059e
Total FENs:    1
Found mates:   1
Best mates:    0
```

**Comment by robertnurnberg** [comment]
Found the bug:
```
info depth 23 seldepth 40 multipv 1 score mate 20 nodes 306711 nps 2621461 hashfull 116 tbhits 0 time 117 pv g3f2 d4e5 f2g3 e5d4 g3c7 g4g3 c7b6 d4e5 b6c7 e5d4 b5b6 h5f3 e4f3 d4d3 b6b7 g3g2 f3g2 d7d6 b7b8q d3d2 b8b5 d2d1 g2f3 d1c1 f3e4 c1d2 b5d3 d2e1 g5f3 e1f2 d3c2 f2g3 c7d6 g3h3 c2h2 h3g4 h2g1 g4h3 d5f4
info depth 24 seldepth 34 multipv 1 score cp 1397 nodes 307643 nps 2629427 hashfull 116 tbhits 0 time 117 pv g3f2 d4e5 f2g3 e5d4 g3c7 g4g3 c7b6 d4e5 b6c7 e5d4 b5b6 h5f3 e4f3 d4d3 b6b7 g3g2 f3g2 d7d6 b7b8q d3d2 b8b6 d2e2
info depth 25 seldepth 36 multipv 1 score cp 1419 nodes 334408 nps 2612562 hashfull 125 tbhits 0 time 128 pv g3f2 d4e5 f2g3 e5d4 g3c7 g4g3 c7b6 d4e5 b6c7 e5d4 b5b6 h5f3 e4f3 d4d3 b6b7 g3g2 f3g2 d7d6 b7b8q d3e2 c7b6 e2e1
info depth 26 seldepth 36 multipv 1 score cp 1419 nodes 1000393 nps 2591691 hashfull 372 tbhits 0 time 386 pv g3f2 d4e5 f2g3 e5d4 g3c7 g4g3 c7b6 d4e5 b6c7 e5d4 b5b6 h5f3 e4f3 d4d3 b6b7 g3g2 f3g2 d7d6 b7b8q d3e2 c7b6 e2e1
bestmove g3f2 ponder d4e5
```

So my new script will count this as mate, even though the final (valid) info line has lost the mate again. Will fix soon.

**Comment by robertnurnberg** [comment]
So here is the corrected output from this PR for `sf-dev`, compare with https://github.com/vondele/matetrack/pull/85#issuecomment-2156625181
```
Using ./stockfish on matetrack.epd with --nodes 1000000
Engine ID:     Stockfish dev-20240608-e271059e
Total FENs:    6556
Found mates:   3419
Best mates:    2518

Parsing the engine's full UCI output, the following issues were detected:
Bad PVs:       3   (from 2 FENs)
```

**Comment by vondele** [comment]
With https://github.com/official-stockfish/Stockfish/pull/5379 no bad PVs are reported any longer, so that's good.

It seems to me post-processing now takes a long time, i.e. after the progress bar reaches the end, there is quite some time left in reality.

**Comment by robertnurnberg** [comment]
Yes, that is due to the many lines per FEN that are now analysed afterwards, And for each line with mate we check the PV for no 3-fold repetition etc.

The progress bar is just for the engine runs themselves.

**Comment by vondele** [comment]
OK, no big issue. 

Probably that could be done in parallel by somehow doing that where the data is collected?

**Pull request merged**
