### PR TITLE
check for lowerbound and upperbound

### PR DESCRIPTION
**Pull request by robertnurnberg**
UCI info lines with these tokens should not count as mate scores.

### CODE REVIEW

**Comment by vondele** [comment]
do you know what the impact of this is on the current matetrack results ?

**Comment by vondele** [comment]
(btw, one recently merged patch has a significant impact on matefinding)

**Comment by robertnurnberg** [comment]
> (btw, one recently merged patch has a significant impact on matefinding)

Interestingly, looking at the graph it seems to be two patches: one reduced overall mates, the other best mates.

In any case, once this one is merged, you may want to re-run the last 50 or so commits anyway? Simply deleteting the last 50 lines from the `.csv` file should to the trick.

**Comment by robertnurnberg** [comment]
Closing in favour of https://github.com/vondele/matetrack/pull/78.

**Pull request closed without merging**
