### PR TITLE
separate fens in .epd from comments with a semicolon

### PR DESCRIPTION
**Pull request by robertnurnberg**
I believe this is a slightly cleaner syntax to separate comments from fens in the .epd file `ChestUCI_23102018.epd`. This way the `bm #M` info becomes just another comment on each line.

Not sure if other projects rely on the current syntax of the best mate encoding per line. 

Feel free to reject the PR if it goes against what you want/need. No offence would be taken. :)

PS: Github does not render the diff of `ChestUCI_23102018.epd` nicely. It was created with the command `sed -i 's/ bm/; bm/' ChestUCI_23102018.epd`.

### CODE REVIEW

**Comment by vondele** [comment]
I suspect I copied the file verbatim from somewhere, so I think it is better not the create a second version of it.

**Comment by robertnurnberg** [comment]
Agreed. Just for future reference, your .epd is probably based on one of the ChestUCI files available on

http://turbotm.de/~heiner/Chess/chest.html

and

https://fhub.jimdofree.com/

**Comment by vondele** [comment]
right, seems likely, on the second page: 

ChestUCI-DB   [Download](https://c.gmx.net/@317206859884790529/te5MtZ0wSWyzxWQuPUFjwA)
Most recent version of ChestUCI-database (>6600 mate problems)

files have the same format as this one.

**Comment by robertnurnberg** [comment]
In fact, the old format adheres to the EPD syntax:

https://www.chessprogramming.org/Extended_Position_Description

where no ";" is allowed between the first four parts of the fen and the extended ops. 

Observe that the creators of the ChestUCI.epd files appear to have changed the interpretation of "bm" from "best move" to "best mate" or similar.

In any case, good that you stick to the old format, which is valid EPD syntax.

**Pull request closed without merging**
