### PR TITLE
WIP: check TB win PV correctness

### PR DESCRIPTION
**Pull request by robertnurnberg**
Maybe this PR as a bit too ambitious. Rather than simply counting the pieces at the end of a TB score PV, I wanted to check the full PV for correctness. So this requires access to the TB in the PV checking function. Unfortunately, the current implementation leads to an error.

I tried to add a lock, but the error persists.

```
> python matecheck.py --engine ./stockfish --epdFile mates2000.epd --syzygyPath /disk2/syzygy/ --nodes 1000
Loaded 2000 FENs, with max(abs(bm)) = 27.

Matetrack started for ./stockfish on mates2000.epd with --nodes 1000 --syzygyPath /disk2/syzygy/ ...
  1%|4                                          | 1/100 [00:00<00:11,  8.52it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rn/git/matetrack/matecheck.py", line 293, in <module>
    res += future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

Maybe @vondele or @Disservin could have a look if that is easily fixable.

(Note that setting `self.tb = None` unconditionally allows some testing of the new code, but then all TB scores will be flagged as having a short PV, because the probing code will return that the position was not found in TB.)

### CODE REVIEW

**Comment by vondele** [comment]
this is an incompatibility between ProcessPoolExecutor and the python code called. Unfortunately, not all code can be passed to ProcessPoolExecutor, only if it is serializable with pickle. So, it looks like the syzygy code internally uses a lock, which can't be serialized.

**Comment by robertnurnberg** [comment]
Hm, thanks for the explanation. Will need to think how to proceed. For example, could forget about probing all nodes along the PV and only check the leaf nodes, in a postprocessing step.

**Comment by robertnurnberg** [comment]
Or we take the time hit and test the tb win pvs as in pr but sequentially in postprocessing. So no change to default behaviour, but tb checking will take much longer.

**Comment by vondele** [comment]
I think SF can only guarantee that the move at which it enters the TB is a TB win, after that, it is search finding the path. So the check probably should be if the PV line enters the TB and if the TB position is a win if the score is a win. 

I'm not particularly sure what happens if exactly when the PV line sees further captures, i.e. what the score would be in a TB position with 5 pieces if the TB is originally 6.

**Comment by robertnurnberg** [comment]
So at present the PR assumes that a correct PV (for mate or TB win) would alternate between +2 and -2 once it enters the PV. Do you think that is too strict? I believe that is a natural assumption for correctness of a PV.

Now because of the concurrency issues of the original PR I will have to drop this check for mate scores. TB wins could still be checked this way in a postprocessing step. It will take longer, but then again we will only use the TB settings very rarely.

**Comment by vondele** [comment]
so, I'm currently not certain what we guarantee for the PV of a TB win/loss score. I think we only guarantee along the PV we enter a TB win/loss position. A correct PV would need to alternate between +2 -2, but I'm not that's guaranteed, IIRC we do not consult the TB for all positions during search. However, if we follow the PV up to the TB position, afterwards, once we are at the root, we will only play winning moves.

**Comment by robertnurnberg** [comment]
Yeah, that's what I understood from your messages. From my point of view, the checks in the script here should be independent from what is currently available or possible in SF.

SF Devs are free to ignore the issues reported by the script. Agreed? So I think I would keep the checks as of now, but refactoring as described above. (When I'm back at keyboard.)

**Comment by vondele** [comment]
yes, that refactoring is fine, and will be interesting.

**Comment by vondele** [comment]
Just FYI, this is where/how we probe TB i search

https://github.com/official-stockfish/Stockfish/blob/2046c92ad461f5e852ba62a144b53c3d3fea04b0/src/search.cpp#L653-L660

**Comment by robertnurnberg** [comment]
Closing in favour of https://github.com/vondele/matetrack/pull/96

**Pull request closed without merging**
