### PR TITLE
correct several wrong mate scores

### PR DESCRIPTION
**Pull request by robertnurnberg**
Correct another wrong mate score in the epd file. See https://github.com/joergoster/Stockfish-old/issues/13#issuecomment-1859137901 and https://discord.com/channels/435943710472011776/1032922913499783169/1185998519077712004

Also remove the (no longer relevant) comment for the mate corrected in https://github.com/vondele/matetrack/pull/7

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Added two more corrections, see https://discord.com/channels/435943710472011776/1032922913499783169/1186613811705303101 and https://discord.com/channels/435943710472011776/1032922913499783169/1186702439202693281

**Comment by robertnurnberg** [comment]
Added one more: https://discord.com/channels/435943710472011776/1032922913499783169/1186923533067092069

PS: I have put this PR as draft, because I want to try to find more before merging. This will make the correction of the historical data easier.

**Comment by robertnurnberg** [comment]
One more: https://discord.com/channels/435943710472011776/1032922913499783169/1186950858664058930

**Comment by robertnurnberg** [comment]
These are all the corrections I can find for now, so this is ready to be merged.

**Comment by robertnurnberg** [comment]
Converted back to draft. Found some more, will try to update over the holidays: 

```
Found better mate #21 for FEN 1R1B4/p6p/rb5P/pk1K2p1/b5p1/1p2p1p1/1P2P1P1/8 w - - bm #23
Found better mate #44 for FEN 7K/8/5Q2/8/6B1/3P3p/p5p1/6kq w - - bm #51
```

```
1R1B4/p6p/rb5P/pk1K2p1/b5p1/1p2p1p1/1P2P1P1/8 w - - bm #21; PV: d8c7 b5b4 c7d6 b4b5 d6g3 b5b4 g3d6 b4b5 b8b7 g4g3 b7h7 g5g4 h7f7 b6c5 f7b7 a6b6 b7b6 c5b6 h6h7 b5a6 h7h8q a4d7 d6g3 a6b7 h8b8 b7a6 d5d6 d7f5 b8g8 a5a4 g8c4 a6b7 c4d5 b7a6 d6c6 f5d7 d5d7 a4a3 d7d3 a6a5 d3b5
```

```
7K/8/5Q2/8/6B1/3P3p/p5p1/6kq w - - bm #44; PV: f6d4 g1f1 d4f4 f1g1 f4e3 g1h2 e3e5 h2g1 g4h5 g1f2 e5f4 f2g1 f4e3 g1f1 e3e2 f1g1 e2e1 g1h2 e1e5 h2g1 h8h7 g1f2 e5e2 f2g3 e2e3 g3h2 e3e5 h2g1 h7g6 g1f2 e5e2 f2g3 e2e3 g3h2 e3e5 h2g1 g6f5 g1f2 e5e2 f2g1 e2e1 g1h2 e1e5 h2g1 f5e4 h1h2 e5a1 g1f2 a1b2 f2g3 b2e5 g3h4 e5f6 h4h5 e4f5 h2f4 f5f4 g2g1q f6h8 h5g6 h8g8 g6f6 g8g1 f6e6 g1g8 e6d7 g8a2 d7c6 f4e4 c6c5 a2h2 c5b4 h2h3 b4c3 h3h2 c3b4 e4d4 b4b5 h2c7 b5a6 c7b8 a6a5 b8b7 a5a4 d4c4 a4a5 b7a7
```

**Comment by dav1312** [comment]
> Found better mate #44 for FEN 7K/8/5Q2/8/6B1/3P3p/p5p1/6kq w - - bm #51

Found mate in 40
```
[FEN "7K/8/5Q2/8/6B1/3P3p/p5p1/6kq w - - 0 1"]
[SetUp "1"]

1.Qd4+ Kf1 2.Qf4+ Kg1 3.Qe3+ Kh2 4.Qe5+ Kg1 5.Bh5 Kf2 6.Qf4+ Kg1 7.Qe3+ Kh2 8.Qe5+ Kg1 9.Kg7 Kf2 10.Qe2+ Kg1 11.Qe1+ Kh2 12.Qe5+ Kg1 13.Kf6 Kf2 14.Qe2+ Kg3 15.Qe3+ Kh2 16.Qe5+ Kg1 17.Kf5 Kf1 18.Qe2+ Kg1 19.Qe1+ Kh2 20.Qe5+ Kg1 21.Ke4 Qh2 22.Qa1+ Kf2 23.Qb2+ Kg3 24.Qe5+ Kh4 25.Qf6+ Kxh5 26.Kf5 Qf4+ 27.Kxf4 g1=Q 28.Qh8+ Kg6 29.Qg8+ Kf6 30.Qxg1 Ke6 31.Qg8+ Ke7 32.Qxa2 Kd6 33.Kf5 Kc5 34.Ke5 Kb4 35.Qc4+ Ka3 36.Kd4 Kb2 37.Qc3+ Ka2 38.Qc2+ Ka3 39.Kc3 h2 40.Qb3# 1-0
```

**Comment by robertnurnberg** [comment]
Added another correction found by @dav1312 , see [discord](https://discord.com/channels/435943710472011776/1032922913499783169/1188652019284709436).

```
[FEN "1r2brk1/pp3p1p/3p1Q2/2pBp3/P2nP3/2NP2P1/1qP2R1P/5RK1 w - - 0 1"]
[SetUp "1"]

1.Nb5 c4 2.Kh1 Rd8 3.Nxd4 Qxd4 4.Rf5 Qe3 5.Rg5+ Qxg5 6.Qxg5+ Kh8 7.Qf6+ Kg8 8.Rf5 h6 9.Qxh6 c3 10.Rg5# 1-0
```

```
info depth 60 seldepth 20 multipv 1 score mate 10 wdl 1000 0 0 nodes 885754646 nps 10327211 hashfull 629 tbhits 0 time 85769 pv c3b5 c5c4 g1h1 b8d8 b5d4 b2d4 f2f5 d4e3 f5g5 e3g5 f6g5 g8h8 g5f6 h8g8 f1f5 h7h6 f6h6 c4c3 f5g5
```

**Comment by robertnurnberg** [comment]
Added two more corrections, see [discord](https://discord.com/channels/435943710472011776/1032922913499783169/1190574002129866832)

**Comment by robertnurnberg** [comment]
I think this is ready to be merged. I do not expect to find more corrections anytime soon.

**Pull request merged**
