### PR TITLE
update some mate scores to matetrack.epd

### PR DESCRIPTION
**Pull request by robertnurnberg**
This PR adjust the old statistics, that were computed on `ChestUCI_23102018.epd`, to the current file `matetrack.epd`, recall https://github.com/vondele/matetrack/pull/7.

The 5 removed, and 1 changed, problems are the following:

```
4k3/b7/1p1p4/pPpPp1p1/P1P1PpPp/5P1P/2QQ4/K7 w - - bm #10; 00:27; 00:03 @ C2/R0/K7/P4/X7;
Nb1QN3/1pp1PPp1/1rnn1p1P/1Pkr2B1/P1pRpK1p/2P1P2B/2qb2Pp/4R3 b - - bm #11; Duals(2); 00:00 @ C3/R0/K5/P3/X6;
Nb1QN3/1pp1PPp1/1rnn1p1P/1Pkr2B1/P1pRpK1p/2P1P2B/2qb2Pp/4R3 w - - bm #12; 00:00 @ C3/R0/K4/P2/X3;
1Brb1B2/Pbn1r3/2pkP3/2p2P2/2Pb1P2/1P1KpP2/1p2P3/4R3 w - - bm #16; --:-- @ C0/R0/K2/P4/X14;
Bk6/1P2p1pp/RP1p3p/P7/2P5/4p3/4p1p1/4Kbrb w - - bm #19; 00:00+;
2r5/1p6/1Nk1p1pn/QpPp1p1r/6p1/nN3b1q/3R4/2BR2K1 w - - bm #25; 00:53 @ C3/R0/K6/P2/X5;
```

The necessary corrections were computed in the branch https://github.com/robertnurnberg/matetrack/tree/correct, see e.g. the file `difference.epd` there for the above list of EPDs. In that branch, the script `do_correct.sh` was used to compute the mate scores for the affected revisions on the six EPDs above. Then the script `correctdata.py` was used to compute the necessary corrections to `matetrack1000000.csv`, and the output saved in `corrected.csv`. 

Here the statistics of the changed scores:
```
Total number of mates in changed positions:  [10, 1189, 1317, 0, 201, 0]
Total number of best mates in changed positions:  [0, 733, 1066, 0, 201, 0]
```
(As expected, the corrected EPD with bm changed from 26 to 25 had no effect whatsoever, making the adjustments to
`matetrack1000000.csv` much easier to compute.)

PS: This PR paves the way for having consistent historical data, also beyond `sf_7`. (Something I am working on.)

### CODE REVIEW

**Comment by vondele** [comment]
Note that perfect backwards compatibility is not there, for example we added a call to ucinewgame after most entries in the csv were computed already. So unless one redoes all calculations, numbers won't be identical. However, I don't think this is strictly needed, the trends from the past might be more interesting and important that the very precise number.

**Comment by vondele** [comment]
That was https://github.com/vondele/matetrack/commit/3d44f6365f6e213b87c954d03ae34cab826730a2

**Comment by robertnurnberg** [comment]
Ok, thanks. So it seems that the first SF commit computed with `ucinewgame` is `442c40b43de8ede1e424efa674c8d45322e3b43c`.

I am stickler for consistency, so would probably only update those numbers that are 100% correct for the current setup.

Those older results we would have to visit another day. I could brute-force recompute them all. Would you accept/trust these numbers coming from me? Might be quite interesting how much `ucinewgame` affects those old data.

**Comment by robertnurnberg** [comment]
Ok, so I amended the PR to only update the scores for the SF commits since the `ucinewgame` change. 

Those overall changed stats are:
```
Total number of mates in changed positions:  [1, 111, 215, 0, 33, 0]
Total number of best mates in changed positions:  [0, 77, 196, 0, 33, 0]
```

Re-computed within branch https://github.com/robertnurnberg/matetrack/tree/partialcorrect

**Comment by vondele** [comment]
> Would you accept/trust these numbers coming from me? Might be quite interesting how much `ucinewgame` affects those old data.

sure, it just takes a while to compute that, getting older revisions would be probably more interesting.

**Comment by robertnurnberg** [comment]
Sure. But my personal preference would be to first get our current data in order, before starting to add new one. There is no rush anyway. So I will start a run to re-compute from `sf_7` to `442c40b43de8ede1e424efa674c8d45322e3b43c`. Thanks to the recent changes to `do_track.sh` this is fairly simple to set up, in a new branch say.

Once that is done, I would do the range `sf_6` to `sf_7`, say, and so on. (Still working on getting the final `exclude_commits.sha` ready for that. This takes time, because the old SF revisions are no-where near as stable as the recent ones.)

**Comment by vondele** [comment]
good, so I'll go ahead an merge this.

**Pull request merged**
