### PR TITLE
new python plots

### PR DESCRIPTION
**Pull request by robertnurnberg**
This PR changes the inner working of matetrack: existing results are no longer stored in 2000+ `out.sha.nodes` files, but within a single `.csv` file. We also store more data for each revision: the precise commit time (allowing true order in plots), the total number of positions tested on, as well as the total number of mates found.

The plotting itself is now done with pyplot.

Some comments:

1. I am open to suggestions for file name changes, plot style changes etc. Nothing is set in stone.
2. Before eventually merging into master, the subdir `outs` as well as the script `convert_outs2csv.sh` can be removed. The latter can be used to create `matetrack1000000.csv` from scratch for a given set of `out.sha.nodes` files.
3. The `git push origin master` part within the script `do_track.sh` will obviously not work from within a non-master branch. So when testing this new version of  `do_track.sh` a manual `git push` can be used to achieve the push for the experimental branch.
4. One possible new type of plot would be mates against commit number (numbered from 1 to 50, say, for the recent results), rather than mates against date. I have not done this yet, as I was not sure whether this is something @vondele  would like to include.

### CODE REVIEW

**Comment by vondele** [comment]
This looks good to me, at least at first sight, without testing.

For the plots I would have a suggestion for the two plots separately:

1) For the 50 last commits plot, can we have two different y-axis for the best mates and total mates. With the current setup, the small changes are hardly visible. This is not so much an issue for the full timeline, as that is anyway having a wider range. I have no strong opinion to using date or commit index for this, but I would like to limit things to two plots, just so the page remains concise. It could be index for the 50 commits, and date for the full range.

2) Not sure this is easy or not, I wonder if we could extract the released versions (i.e. git tagged with sf_[0-9]*.[0-9]*) and add a label to the data points in the graph (one way or another), for example as in the top graph on https://nextchessmove.com/dev-builds

**Comment by robertnurnberg** [comment]
Ok, I have done 1. Do you think we need a label (like "commit") for the x-axis?

About 2. I would need to think some more. Is the text needed for the label already in the csv file? Would you want to label each data point? Would it be for both or just one of the two plots? (I am not yet able to create interactive plots: just simple `.png` from me for now. ;) )

One could also do something simpler like a vertical line for each major sf release? Or indeed a label for the corresponding data point. But I am not quite sure how to obtain the necessary info and where and how to store it best.

**Comment by vondele** [comment]
fine with what you prefer. Intuitively, I would use a different comma separated field for the tags, but merging them could also be fine, I don't know what the conventions for csv are.

**Comment by robertnurnberg** [comment]
Yeah, did not want to mess with the order of the columns. But could have tag indeed as final column.

**Comment by robertnurnberg** [comment]
Tags are now added. I did not test yet if the tag addition in the script `do_track.sh` also works as expected. Will do so later today just to be safe. Can also squash into single commit if you want.

**Comment by vondele** [comment]
thanks, this looks nice.

So, I'll go ahead and merge that in the outputs branch. 

Next up will be merging things into master.

**Comment by vondele** [comment]
so the merge into master somehow didn't keep this history well, probably as I messed around with rebasing commits to avoid merging the outputs. 

Looking at the first graph. Would it make sense to index the 50 commits in the graph from -49 .... 0, i.e. so that it is clear that the most recent commit is on the right ?

**Comment by robertnurnberg** [comment]
Sorry to hear that. Am afk now. Do you need help to fix it? If you still have the outputs branch, you can start from scratch with your `out.` files, first deleting any CSV file and then running the convert script.

Ok about the indexing.

**Comment by vondele** [comment]
I think all is fine with the out files, current state is good, the main issue is that you're not listed as the author for that merge into master. So no worries or urgency.

**Comment by robertnurnberg** [comment]
Oh, our wires crossed. :) I thought history referred to the revision history/mate tracking. No worries at all about commit history. No need to change anything.

**Pull request merged**
