### PR TITLE
add results from between sf4 and sf7

### PR DESCRIPTION
**Pull request by robertnurnberg**
This PR proposes to add historical data from between sf4 and sf7 to matetrack. It is based on top of both https://github.com/vondele/matetrack/pull/17 and https://github.com/vondele/matetrack/pull/18.

The raw data was computed in the following branches on my fork:

- https://github.com/robertnurnberg/matetrack/tree/sf6sf7
- https://github.com/robertnurnberg/matetrack/tree/sf5sf6
- https://github.com/robertnurnberg/matetrack/tree/sf4sf5

Some observations: some of the `matecheck.py` runs for these early SF revisions do not seem to be deterministic. (I have noted that especially before sf4  the spawned `stockfish` processes are not always single-threaded, even though they should be.)

An example are the two different lines in the above raw data for `sf_5`:
```
2014-05-31T09:16:54+02:00,54f8a9cb138a1bc0b0054b98f911fafd8d1b03ad,6561,2486,1753,sf_5^{}
2014-05-31T09:16:54+02:00,54f8a9cb138a1bc0b0054b98f911fafd8d1b03ad,6561,2483,1753,sf_5^{}
```

(For the PR I chose the second line.)

Moreover, weirdly, the first few entries in the raw data in https://github.com/robertnurnberg/matetrack/tree/sf6sf7 are for commits from _before_ the `sf_6` release. The reason seems to be this output from the command `git rev-list --reverse 5b555525d2f9cbff446b7461d1317948e8e21cd1^..dd9cf305816c84c2acfa11cae09a31c4d77cc5a5`:
```
3c07603dac03f0da20194097cf4eb1a396fea60d
f53aea45e3230239d358d4d35357c9ee6bf6fb54
f7d8ea3866c26df10617e97513e906d1f5a5b833
fe4fda474fb8b0cb582c8232be602e2d323c87eb
712bbb052eb19f04d184da3d9ba66ae11f565201
ca3622f8e86746b066f75db449b1e8beac111b6c
f54c44e6be0deaadefcb428af8d288e75955aa20
2ca2c3f35b2e408fd97bdf7092f41e1e508eb7af
96e36a789708164b14c873cdb2e0acac9aca57e7
36f8814aa6369a9bce1216556d9382cac34b4678
6390a3da9471da3e0e8755eceb11225fc3088836
18375e3bfbd03b0851969bda5427d5b22cb4fea1
69407ae9b88d9fd7e8b724f1a8bf1f47bb4d2f67
14f7d9a6292ac7c2e92d9bcab7dd7186eb151c02
5b555525d2f9cbff446b7461d1317948e8e21cd1        <--- sf_6
9f0d5241bfcf454d4b21594b0af239bbe5990b84
7837fb2aca6db425e5f7237f5cc714412fc0140d
```

Unfortunately, I do not know enough about git to explain this. What I did was to manually insert those commits appearing before `sf_6` into the overall csv file, so that all the commits are sorted by commit date/time. There was no duplication of commits.

### CODE REVIEW

**Comment by vondele** [comment]
I think older versions were not necessarily deterministic or led to the same results after ucinewgame. I think that's ok. 

One of the labels on the graph looks wrong.

**Comment by robertnurnberg** [comment]
Do you mean `sf_5^{}`? That is the release label as reported by `git`, see also the two lines above with different results. If we wish we can beautify some labels, can be done within `do_track.sh` or within the plotting function. Maybe the former is cleaner.

**Comment by robertnurnberg** [comment]
I amended the label and ensured labels do not overlap (for now). If that is better I can squash both commits into one. Let me know,  tumbs up suffices.

**Comment by vondele** [comment]
@robertnurnberg could you please rebase this PR on the current master, I have merged the other PRs, now this one seems to have some conflicts.

**Comment by robertnurnberg** [comment]
done

**Comment by vondele** [comment]
merged, I'll try to run the local update now for master, to see if that works fine.

**Comment by robertnurnberg** [comment]
Fingers crossed. :)

**Comment by vondele** [comment]
worked fine.

**Pull request merged**
